import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateSurveyResponsesTables1776612897477 implements MigrationInterface {
    name = 'CreateSurveyResponsesTables1776612897477'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "surveys_responses" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "submitted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "survey_id" integer NOT NULL, "user_id" integer, CONSTRAINT "PK_393a3d96fa12378871e32857c43" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "survey_response_answers" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "value" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "survey_response_id" integer NOT NULL, "survey_field_id" integer NOT NULL, "survey_option_id" integer, CONSTRAINT "PK_66e89e106eb547a390bea6c096f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "surveys_responses" ADD CONSTRAINT "FK_bfea082f96aec9bc908b6216547" FOREIGN KEY ("survey_id") REFERENCES "surveys"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surveys_responses" ADD CONSTRAINT "FK_071bb443586baea93291066041f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_response_answers" ADD CONSTRAINT "FK_4c53ab67bcc1d5ec3792e31935f" FOREIGN KEY ("survey_response_id") REFERENCES "surveys_responses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_response_answers" ADD CONSTRAINT "FK_6cf9a3752f2d8b32002738d14a0" FOREIGN KEY ("survey_field_id") REFERENCES "survey_fields"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_response_answers" ADD CONSTRAINT "FK_aee5fe7ad824b6815115af3fce2" FOREIGN KEY ("survey_option_id") REFERENCES "survey_field_options"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "survey_response_answers" DROP CONSTRAINT "FK_aee5fe7ad824b6815115af3fce2"`);
        await queryRunner.query(`ALTER TABLE "survey_response_answers" DROP CONSTRAINT "FK_6cf9a3752f2d8b32002738d14a0"`);
        await queryRunner.query(`ALTER TABLE "survey_response_answers" DROP CONSTRAINT "FK_4c53ab67bcc1d5ec3792e31935f"`);
        await queryRunner.query(`ALTER TABLE "surveys_responses" DROP CONSTRAINT "FK_071bb443586baea93291066041f"`);
        await queryRunner.query(`ALTER TABLE "surveys_responses" DROP CONSTRAINT "FK_bfea082f96aec9bc908b6216547"`);
        await queryRunner.query(`DROP TABLE "survey_response_answers"`);
        await queryRunner.query(`DROP TABLE "surveys_responses"`);
    }

}
