import { ValidationError, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { ApiExceptionFilter } from './common/filters/ApiException.filter';
import { ClientException } from './common/errors/Client.exception';
import { setupSwagger } from './config/Swagger.config';

/**
 * Converts class-validator errors into the standard API error data format.
 *
 * @param {ValidationError[]} errors - Validation errors generated by ValidationPipe.
 * @returns {{ field: string; message: string }[]} The normalized validation error list.
 */
function formatValidationErrors(
  errors: ValidationError[],
): { field: string; message: string }[] {
  return errors.flatMap((error) => {
    if (error.constraints) {
      return Object.values(error.constraints).map((message) => ({
        field: error.property,
        message,
      }));
    }

    return [
      {
        field: error.property,
        message: 'invalid value',
      },
    ];
  });
}

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.enableShutdownHooks();
  app.useGlobalFilters(new ApiExceptionFilter());
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transform: true,
      forbidNonWhitelisted: true,
      exceptionFactory: (errors: ValidationError[]) =>
        new ClientException(
          'validation error',
          'erro de validação',
          formatValidationErrors(errors),
        ),
    }),
  );
  setupSwagger(app);
  await app.listen(process.env.PORT ?? 3000);
}
void bootstrap();
